# image: python:slim # debian
image: mcr.microsoft.com/dotnet/sdk:7.0

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            # Install deps
            - apt-get update && apt-get install -y python3 python3-venv p7zip-full
            # Check python version
            - /usr/bin/python3 --version
            # Create virtual env (after this, can use "python" in commands)
            - /usr/bin/python3 -m venv venv
            - source venv/bin/activate
            # Install pip
            - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - python get-pip.py --prefix=venv
            # Install build script deps
            - venv/bin/pip install -r ./build/requirements.txt
            # Initialize git submodule
            - git submodule update --init --recursive --depth=1
            # Run build script
            - python ./build/build.py
            # Identify all files inside dist directory
            - ls -lR dist
          artifacts:
            - dist/*.zip
      - step:
          name: Upload Artifact
          script:
            - ls -lR dist # identify all files inside dist directory
            - pipe: atlassian/bitbucket-upload-file:0.3.4
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "**/*.zip"
