# image: python:slim # debian
image: mcr.microsoft.com/dotnet/sdk:7.0

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - echo 'Installing deps (git, 7-Zip)'
            - apt-get update && apt-get install -y python3 python3-venv p7zip-full
            - echo "Python version check"
            - /usr/bin/python3 --version
            - echo 'Creating virtual environment'
            - /usr/bin/python3 -m venv venv
            - source venv/bin/activate
            - echo 'Installing pip'
            - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - /usr/bin/python3 get-pip.py
            - echo "Install Python deps"
            - /usr/local/bin/pip install -r ./build/requirements.txt
            - echo 'Initializing dependencies submodule'
            - git submodule update --init --recursive --depth=1
            - echo "Running build script"
            - /usr/bin/python3 ./build/build.py
            - ls -lR dist # identify all files inside dist directory
          artifacts:
            - dist/*.zip
      - step:
          name: Upload Artifact
          script:
            - ls -lR dist # identify all files inside dist directory
            - pipe: atlassian/bitbucket-upload-file:0.3.4
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "**/*.zip"
