on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3 python3-venv openssh-server libc6
          python3 -m venv venv
          source venv/bin/activate
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py --prefix=venv
          venv/bin/pip install -r ./build/requirements.txt
      - name: Run build script
        run: |
          source venv/bin/activate
          python ./build/ci.py
      - name: Identify all files inside dist directory
        run: ls -lR dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.zip
