on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3 python3-venv openssh-server
          python3 -m venv venv
          source venv/bin/activate
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py --prefix=venv
          venv/bin/pip install -r ./build/requirements.txt

      - name: Run build script
        run: |
          source venv/bin/activate
          python ./build/ci.py

      - name: Identify all files inside dist directory
        run: ls -lR dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.zip

  # upload-artifact:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: dist

  #     - name: Identify all files inside dist directory
  #       run: ls -lR dist

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: release-artifact
  #         path: path/to/your/artifact